server:
    port: 8888

spring:
  datasource:
    url: jdbc:mysql://rm-uf6uz3043ca8dbnw6o.mysql.rds.aliyuncs.com:3306/pu_store_new?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true&useSSL=true
    password: Pop123456789
    username: popupunion
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.richard.cloud.dao
  mapper-locations: classpath*:mapper/*.xml

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql





